# Generated by Django 5.0.1 on 2024-03-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='images/default1.jpg', upload_to='images')),
                ('email', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
    ]
