# Generated by Django 5.0.1 on 2024-03-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_alter_employee_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='description',
        ),
    ]
